version: '3.8'

services:
    web:
        build: ./$REPONAME
        environment:
            - "UseInMemoryDatabase=false"
            - "ConnectionStrings__DefaultConnection=Server=db;Database=CleanArchitectureDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true"
            - "ASPNETCORE_URLS=http://+:80"
            - "ASPNETCORE_ENVIRONMENT=Development"
        ports:
            - 8000:80
        depends_on:
            - db
    db:
        image: mcr.microsoft.com/mssql/server
        environment:
            - "SA_PASSWORD=Your_password123"
            - "ACCEPT_EULA=Y"